export interface ContentTypeDefinition {
  id: string;
  name: string;
  description?: string;
  displayField?: string;
  fields: Array<{
    id: string;
    name: string;
    type: string;
    required?: boolean;
    localized?: boolean;
    validations?: Array<Record<string, unknown>>;
    items?: Record<string, unknown>;
    linkType?: string;
    disabled?: boolean;
    omitted?: boolean;
  }>;
}

export const PUBLIC_CONTENT_MODELS: ContentTypeDefinition[] = [
  {
    id: "instructorProfile",
    name: "Instructor Profile",
    displayField: "name",
    fields: [
      { id: "name", name: "Name", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "headline", name: "Headline", type: "Symbol" },
      { id: "bio", name: "Bio", type: "Text", required: true },
      { id: "credentials", name: "Credentials", type: "Array", items: { type: "Symbol" } },
      { id: "specialties", name: "Specialties", type: "Array", items: { type: "Symbol" } },
      { id: "avatarImageUrl", name: "Avatar Image Url", type: "Symbol" },
      { id: "avatarAlt", name: "Avatar Alt", type: "Symbol" },
      { id: "featuredQuote", name: "Featured Quote", type: "Text" },
      { id: "active", name: "Active", type: "Boolean" },
      { id: "seoTitle", name: "SEO Title", type: "Symbol" },
      { id: "seoDescription", name: "SEO Description", type: "Text" },
    ],
  },
  {
    id: "classDefinition",
    name: "Class Definition",
    displayField: "name",
    fields: [
      { id: "name", name: "Name", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      {
        id: "type",
        name: "Type",
        type: "Symbol",
        required: true,
        validations: [{ in: ["Yoga", "Strength", "HIIT"] }],
      },
      {
        id: "classCategory",
        name: "Class Category",
        type: "Symbol",
        required: true,
        validations: [{ in: ["yoga", "strength", "small-group"] }],
      },
      { id: "level", name: "Level", type: "Symbol", required: true },
      { id: "defaultDay", name: "Default Day", type: "Symbol" },
      { id: "defaultTime", name: "Default Time", type: "Symbol" },
      { id: "duration", name: "Duration", type: "Symbol", required: true },
      { id: "maxCapacity", name: "Max Capacity", type: "Integer", required: true },
      { id: "shortDescription", name: "Short Description", type: "Text", required: true },
      { id: "longDescription", name: "Long Description", type: "Text", required: true },
      { id: "whatToExpect", name: "What To Expect", type: "Array", items: { type: "Symbol" } },
      { id: "whoItsFor", name: "Who It's For", type: "Array", items: { type: "Symbol" } },
      { id: "equipment", name: "Equipment", type: "Array", items: { type: "Symbol" } },
      { id: "benefits", name: "Benefits", type: "Array", items: { type: "Symbol" } },
      {
        id: "defaultInstructorProfile",
        name: "Default Instructor Profile",
        type: "Link",
        linkType: "Entry",
        validations: [{ linkContentType: ["instructorProfile"] }],
      },
      { id: "seoTitle", name: "SEO Title", type: "Symbol" },
      { id: "seoDescription", name: "SEO Description", type: "Text" },
      { id: "seoKeywords", name: "SEO Keywords", type: "Text" },
    ],
  },
  {
    id: "smallGroupProgramme",
    name: "Small Group Programme Template",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "subtitle", name: "Subtitle", type: "Text" },
      { id: "shortSummary", name: "Short Summary", type: "Text", required: true },
      { id: "fullDescription", name: "Full Description", type: "Text" },
      { id: "longDescription", name: "Long Description", type: "Text" },
      {
        id: "outcomes",
        name: "Outcomes",
        type: "Array",
        items: { type: "Symbol" },
      },
      { id: "durationLabel", name: "Duration Label", type: "Symbol", required: true },
      { id: "durationWeeks", name: "Duration Weeks", type: "Integer" },
      { id: "cohortSize", name: "Default Cohort Size", type: "Integer", required: true },
      { id: "sessionsPerWeek", name: "Sessions Per Week", type: "Integer" },
      { id: "defaultPricePence", name: "Default Price Pence", type: "Integer" },
      { id: "whoItsFor", name: "Who It's For", type: "Array", items: { type: "Symbol" } },
      { id: "equipment", name: "Equipment", type: "Array", items: { type: "Symbol" } },
      { id: "inclusions", name: "Inclusions", type: "Array", items: { type: "Symbol" } },
      { id: "weekByWeek", name: "Week By Week", type: "Object" },
    ],
  },
  {
    id: "retreatVenue",
    name: "Retreat Venue",
    displayField: "name",
    fields: [
      { id: "name", name: "Name", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "displayLocation", name: "Display Location", type: "Symbol", required: true },
      { id: "description", name: "Description", type: "Text" },
      { id: "address", name: "Address", type: "Text" },
      { id: "addressLine1", name: "Address Line 1", type: "Symbol" },
      { id: "addressLine2", name: "Address Line 2", type: "Symbol" },
      { id: "townOrCity", name: "Town or City", type: "Symbol" },
      { id: "region", name: "Region", type: "Symbol" },
      { id: "postcode", name: "Postcode", type: "Symbol" },
      { id: "country", name: "Country", type: "Symbol" },
      {
        id: "accommodationOptions",
        name: "Accommodation Options",
        type: "Array",
        items: { type: "Symbol" },
      },
      { id: "travelInformation", name: "Travel Information", type: "Text" },
      { id: "arrivalInformation", name: "Arrival Information", type: "Text" },
      { id: "travelByTrain", name: "Travel by Train", type: "Text" },
      { id: "travelByCar", name: "Travel by Car", type: "Text" },
      { id: "travelByAir", name: "Travel by Air", type: "Text" },
      {
        id: "localTransferInformation",
        name: "Local Transfer Information",
        type: "Text",
      },
      { id: "accommodationType", name: "Accommodation Type", type: "Text" },
      { id: "facilities", name: "Facilities", type: "Array", items: { type: "Symbol" } },
      { id: "accessibilityNotes", name: "Accessibility Notes", type: "Text" },
      {
        id: "kitchenAccessDescription",
        name: "Kitchen Access Description",
        type: "Text",
      },
    ],
  },
  {
    id: "retreatScheduleDay",
    name: "Retreat Schedule Day",
    description: "A retreat day with an optional subtitle and a simple activity list.",
    displayField: "title",
    fields: [
      { id: "title", name: "Day title", type: "Symbol", required: true },
      { id: "subtitle", name: "Day subtitle (optional)", type: "Symbol" },
      {
        id: "activities",
        name: "Activities (one per line)",
        type: "Text",
      },
      {
        id: "slug",
        name: "Legacy internal slug",
        type: "Symbol",
        disabled: true,
        omitted: false,
      },
      {
        id: "dayLabel",
        name: "Legacy day label",
        type: "Symbol",
        disabled: true,
        omitted: false,
      },
      {
        id: "displayOrder",
        name: "Legacy display order",
        type: "Integer",
        disabled: true,
        omitted: false,
      },
      {
        id: "items",
        name: "Legacy linked activities",
        type: "Array",
        disabled: true,
        omitted: false,
        items: {
          type: "Link",
          linkType: "Entry",
          validations: [{ linkContentType: ["retreatScheduleItem"] }],
        },
      },
    ],
  },
  {
    id: "retreatTemplate",
    name: "Retreat Template",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "subtitle", name: "Subtitle", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "shortDescription", name: "Short Description", type: "Text", required: true },
      { id: "fullDescription", name: "Full Description", type: "Text", required: true },
      {
        id: "experienceType",
        name: "Experience Type",
        type: "Symbol",
        required: true,
        validations: [
          {
            in: [
              "residential_retreat",
              "day_retreat",
              "online_workshop",
              "in_person_workshop",
              "course",
            ],
          },
        ],
      },
      {
        id: "deliveryMode",
        name: "Delivery Mode",
        type: "Symbol",
        required: true,
        validations: [{ in: ["in_person", "online_live", "online_on_demand", "hybrid"] }],
      },
      { id: "durationLabel", name: "Duration Label", type: "Symbol", required: true },
      { id: "audienceDescription", name: "Audience Description", type: "Text" },
      { id: "experienceLevel", name: "Experience Level", type: "Symbol" },
      { id: "heroImage", name: "Hero Image", type: "Link", linkType: "Asset" },
      { id: "heroImageUrl", name: "Hero Image URL", type: "Symbol" },
      {
        id: "gallery",
        name: "Gallery",
        type: "Array",
        items: { type: "Link", linkType: "Asset" },
      },
      { id: "suitableFor", name: "Suitable For", type: "Array", items: { type: "Symbol" } },
      { id: "included", name: "Included", type: "Array", items: { type: "Symbol" } },
      { id: "notIncluded", name: "Not Included", type: "Array", items: { type: "Symbol" } },
      { id: "whatToBring", name: "What to Bring", type: "Array", items: { type: "Symbol" } },
      {
        id: "foodAndDrinkDescription",
        name: "Food and Drink Description",
        type: "Text",
      },
      {
        id: "scheduleDays",
        name: "Schedule",
        type: "Array",
        items: {
          type: "Link",
          linkType: "Entry",
          validations: [{ linkContentType: ["retreatScheduleDay"] }],
        },
      },
      {
        id: "schedule",
        name: "Legacy Schedule (fallback)",
        type: "Object",
        disabled: true,
        omitted: false,
      },
      { id: "accommodationDescription", name: "Accommodation Description", type: "Text" },
      {
        id: "venue",
        name: "Venue",
        type: "Link",
        linkType: "Entry",
        validations: [{ linkContentType: ["retreatVenue"] }],
      },
      { id: "seoTitle", name: "SEO Title", type: "Symbol" },
      { id: "seoDescription", name: "SEO Description", type: "Text" },
    ],
  },
  {
    id: "authorProfile",
    name: "Author Profile",
    displayField: "name",
    fields: [
      { id: "name", name: "Name", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "role", name: "Role", type: "Symbol" },
      { id: "bio", name: "Bio", type: "Text", required: true },
      { id: "avatarImageAsset", name: "Avatar Image", type: "Link", linkType: "Asset" },
      { id: "avatarImageUrl", name: "Avatar Image Url", type: "Symbol" },
      { id: "avatarAlt", name: "Avatar Alt", type: "Symbol" },
      { id: "websiteUrl", name: "Website Url", type: "Symbol" },
      { id: "instagramHandle", name: "Instagram Handle", type: "Symbol" },
      { id: "isGuestContributor", name: "Is Guest Contributor", type: "Boolean" },
      { id: "active", name: "Active", type: "Boolean" },
    ],
  },
  {
    id: "blogPost",
    name: "Blog Post",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      {
        id: "coverImageAsset",
        name: "Cover Image Asset",
        type: "Link",
        linkType: "Asset",
        validations: [{ linkMimetypeGroup: ["image"] }],
      },
      { id: "coverImageUrl", name: "Cover Image URL", type: "Symbol" },
      { id: "coverAlt", name: "Cover Alt", type: "Symbol" },
      { id: "excerpt", name: "Excerpt", type: "Text", required: true },
      { id: "content", name: "Content", type: "Text", required: true },
      {
        id: "category",
        name: "Brand Category",
        type: "Symbol",
        validations: [{ in: ["rehabilitation", "fitness", "wellbeing"] }],
      },
      {
        id: "authors",
        name: "Authors",
        type: "Array",
        items: {
          type: "Link",
          linkType: "Entry",
          validations: [{ linkContentType: ["authorProfile"] }],
        },
      },
      { id: "tags", name: "Tags", type: "Array", items: { type: "Symbol" } },
      { id: "readTime", name: "Read Time", type: "Symbol" },
      { id: "seoTitle", name: "SEO Title", type: "Symbol" },
      { id: "seoDescription", name: "SEO Description", type: "Text" },
    ],
  },
  {
    id: "testimonial",
    name: "Testimonial",
    displayField: "authorName",
    fields: [
      { id: "slug", name: "Slug", type: "Symbol", validations: [{ unique: true }] },
      { id: "quote", name: "Quote", type: "Text", required: true },
      { id: "authorName", name: "Author Name", type: "Symbol", required: true },
      { id: "featured", name: "Featured", type: "Boolean" },
    ],
  },
  {
    id: "faqItem",
    name: "FAQ Item",
    displayField: "question",
    fields: [
      { id: "question", name: "Question", type: "Symbol", required: true },
      { id: "answer", name: "Answer", type: "Text", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "category", name: "Category", type: "Symbol" },
      {
        id: "targetPage",
        name: "Target Page",
        type: "Symbol",
        validations: [
          {
            in: [
              "general",
              "home",
              "classes",
              "classes-yoga",
              "classes-strength",
              "classes-small-groups",
              "pt",
              "pricing",
              "retreats",
              "retreat-detail",
              "schedule",
              "schedule-detail",
              "blog",
              "blog-post",
              "about",
              "contact",
            ],
          },
        ],
      },
      { id: "targetSection", name: "Target Section", type: "Symbol" },
      { id: "sortOrder", name: "Sort Order", type: "Integer" },
    ],
  },
  {
    id: "leadMagnet",
    name: "Lead Magnet",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "hookText", name: "Hook Text", type: "Text", required: true },
      { id: "landingHeadline", name: "Landing Headline", type: "Symbol" },
      { id: "landingDescription", name: "Landing Description", type: "Text" },
      { id: "ctaLabel", name: "CTA Label", type: "Symbol" },
      { id: "emailSubject", name: "Email Subject", type: "Symbol", required: true },
      { id: "emailPreviewText", name: "Email Preview Text", type: "Symbol" },
      { id: "emailBody", name: "Email Body", type: "Text", required: true },
      {
        id: "deliveryType",
        name: "Delivery Type",
        type: "Symbol",
        required: true,
        validations: [{ in: ["link", "inline"] }],
      },
      { id: "assetUrl", name: "Asset URL", type: "Symbol" },
      { id: "active", name: "Active", type: "Boolean" },
      { id: "startAt", name: "Start At", type: "Date" },
      { id: "endAt", name: "End At", type: "Date" },
    ],
  },
  {
    id: "newsletterSignupContent",
    name: "Newsletter Signup Content",
    displayField: "slug",
    fields: [
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      {
        id: "activeLeadMagnet",
        name: "Active Lead Magnet",
        type: "Link",
        linkType: "Entry",
        required: true,
        validations: [{ linkContentType: ["leadMagnet"] }],
      },
      { id: "formPlaceholder", name: "Form Placeholder", type: "Symbol", required: true },
      { id: "buttonLabel", name: "Button Label", type: "Symbol", required: true },
      { id: "successMessage", name: "Success Message", type: "Symbol", required: true },
      { id: "consentText", name: "Consent Text", type: "Text", required: true },
      { id: "popupTitle", name: "Popup Title", type: "Symbol" },
      { id: "popupDescription", name: "Popup Description", type: "Text" },
    ],
  },
  {
    id: "newsletterTemplate",
    name: "Newsletter Template",
    displayField: "title",
    fields: [
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "subject", name: "Subject", type: "Symbol", required: true },
      { id: "previewText", name: "Preview Text", type: "Symbol" },
      {
        id: "content",
        name: "Content",
        type: "RichText",
        validations: [
          {
            enabledNodeTypes: [
              "heading-2",
              "heading-3",
              "heading-4",
              "ordered-list",
              "unordered-list",
              "hr",
              "blockquote",
              "hyperlink",
              "embedded-asset-block",
            ],
          },
        ],
      },
      { id: "body", name: "Legacy Body", type: "Text", omitted: true },
      {
        id: "segmentation",
        name: "Segmentation",
        type: "Symbol",
        validations: [{ in: ["all_subscribers"] }],
      },
    ],
  },
];
