export interface ContentTypeDefinition {
  id: string;
  name: string;
  description?: string;
  displayField?: string;
  fields: Array<{
    id: string;
    name: string;
    type: string;
    required?: boolean;
    localized?: boolean;
    validations?: Array<Record<string, unknown>>;
    items?: Record<string, unknown>;
    linkType?: string;
    disabled?: boolean;
    omitted?: boolean;
  }>;
}

export const PUBLIC_CONTENT_MODELS: ContentTypeDefinition[] = [
  {
    id: "globalContent",
    name: "Global Content",
    displayField: "siteName",
    fields: [
      { id: "siteName", name: "Site Name", type: "Symbol", required: true },
      { id: "siteTagline", name: "Site Tagline", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      {
        id: "defaultSeoDescription",
        name: "Default SEO Description",
        type: "Text",
        required: true,
      },
      { id: "headerNavItems", name: "Header Nav Items", type: "Object" },
      { id: "footerNavGroups", name: "Footer Nav Groups", type: "Object" },
      { id: "announcementBar", name: "Announcement Bar", type: "Object" },
    ],
  },
  {
    id: "instructorProfile",
    name: "Instructor Profile",
    displayField: "name",
    fields: [
      { id: "name", name: "Name", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "headline", name: "Headline", type: "Symbol" },
      { id: "bio", name: "Bio", type: "Text", required: true },
      { id: "credentials", name: "Credentials", type: "Array", items: { type: "Symbol" } },
      { id: "specialties", name: "Specialties", type: "Array", items: { type: "Symbol" } },
      { id: "avatarImageUrl", name: "Avatar Image Url", type: "Symbol" },
      { id: "avatarAlt", name: "Avatar Alt", type: "Symbol" },
      { id: "featuredQuote", name: "Featured Quote", type: "Text" },
      { id: "active", name: "Active", type: "Boolean" },
      { id: "seoTitle", name: "SEO Title", type: "Symbol" },
      { id: "seoDescription", name: "SEO Description", type: "Text" },
    ],
  },
  {
    id: "classDefinition",
    name: "Class Definition",
    displayField: "name",
    fields: [
      { id: "name", name: "Name", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      {
        id: "type",
        name: "Type",
        type: "Symbol",
        required: true,
        validations: [{ in: ["Yoga", "Strength", "HIIT"] }],
      },
      {
        id: "classCategory",
        name: "Class Category",
        type: "Symbol",
        required: true,
        validations: [{ in: ["yoga", "strength", "small-group"] }],
      },
      { id: "level", name: "Level", type: "Symbol", required: true },
      { id: "defaultDay", name: "Default Day", type: "Symbol" },
      { id: "defaultTime", name: "Default Time", type: "Symbol" },
      { id: "duration", name: "Duration", type: "Symbol", required: true },
      { id: "maxCapacity", name: "Max Capacity", type: "Integer", required: true },
      { id: "shortDescription", name: "Short Description", type: "Text", required: true },
      { id: "longDescription", name: "Long Description", type: "Text", required: true },
      { id: "whatToExpect", name: "What To Expect", type: "Array", items: { type: "Symbol" } },
      { id: "whoItsFor", name: "Who It's For", type: "Array", items: { type: "Symbol" } },
      { id: "equipment", name: "Equipment", type: "Array", items: { type: "Symbol" } },
      { id: "benefits", name: "Benefits", type: "Array", items: { type: "Symbol" } },
      {
        id: "defaultInstructorProfile",
        name: "Default Instructor Profile",
        type: "Link",
        linkType: "Entry",
        validations: [{ linkContentType: ["instructorProfile"] }],
      },
      { id: "seoTitle", name: "SEO Title", type: "Symbol" },
      { id: "seoDescription", name: "SEO Description", type: "Text" },
      { id: "seoKeywords", name: "SEO Keywords", type: "Text" },
    ],
  },
  {
    id: "themedWeekPromo",
    name: "Themed Week Promo",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "shortDescription", name: "Short Description", type: "Text", required: true },
      { id: "audience", name: "Audience", type: "Text", required: true },
      { id: "ctaHref", name: "CTA Href", type: "Symbol", required: true },
      { id: "ctaLabel", name: "CTA Label", type: "Symbol", required: true },
      {
        id: "status",
        name: "Status",
        type: "Symbol",
        validations: [{ in: ["upcoming", "current", "waitlist"] }],
      },
      { id: "sortOrder", name: "Sort Order", type: "Integer" },
      { id: "active", name: "Active", type: "Boolean" },
    ],
  },
  {
    id: "smallGroupProgramme",
    name: "Small Group Programme Template",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "subtitle", name: "Subtitle", type: "Text" },
      { id: "shortSummary", name: "Short Summary", type: "Text", required: true },
      { id: "fullDescription", name: "Full Description", type: "Text" },
      { id: "longDescription", name: "Long Description", type: "Text" },
      {
        id: "outcomes",
        name: "Outcomes",
        type: "Array",
        items: { type: "Symbol" },
      },
      { id: "durationLabel", name: "Duration Label", type: "Symbol", required: true },
      { id: "durationWeeks", name: "Duration Weeks", type: "Integer" },
      { id: "cohortSize", name: "Default Cohort Size", type: "Integer", required: true },
      { id: "sessionsPerWeek", name: "Sessions Per Week", type: "Integer" },
      { id: "defaultPricePence", name: "Default Price Pence", type: "Integer" },
      { id: "whoItsFor", name: "Who It's For", type: "Array", items: { type: "Symbol" } },
      { id: "equipment", name: "Equipment", type: "Array", items: { type: "Symbol" } },
      { id: "inclusions", name: "Inclusions", type: "Array", items: { type: "Symbol" } },
      { id: "weekByWeek", name: "Week By Week", type: "Object" },
    ],
  },
  {
    id: "retreatVenue",
    name: "Retreat Venue",
    displayField: "name",
    fields: [
      { id: "name", name: "Name", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "displayLocation", name: "Display Location", type: "Symbol", required: true },
      { id: "description", name: "Description", type: "Text" },
      { id: "address", name: "Address", type: "Text" },
      {
        id: "accommodationOptions",
        name: "Accommodation Options",
        type: "Array",
        items: { type: "Symbol" },
      },
      { id: "travelInformation", name: "Travel Information", type: "Text" },
      { id: "accommodationType", name: "Accommodation Type", type: "Text" },
      { id: "facilities", name: "Facilities", type: "Array", items: { type: "Symbol" } },
      { id: "accessibilityNotes", name: "Accessibility Notes", type: "Text" },
    ],
  },
  {
    id: "retreatTemplate",
    name: "Retreat Template",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "subtitle", name: "Subtitle", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "shortDescription", name: "Short Description", type: "Text", required: true },
      { id: "fullDescription", name: "Full Description", type: "Text", required: true },
      { id: "suitableFor", name: "Suitable For", type: "Array", items: { type: "Symbol" } },
      { id: "included", name: "Included", type: "Array", items: { type: "Symbol" } },
      { id: "notIncluded", name: "Not Included", type: "Array", items: { type: "Symbol" } },
      {
        id: "venue",
        name: "Venue",
        type: "Link",
        linkType: "Entry",
        validations: [{ linkContentType: ["retreatVenue"] }],
      },
      { id: "seoTitle", name: "SEO Title", type: "Symbol" },
      { id: "seoDescription", name: "SEO Description", type: "Text" },
    ],
  },
  {
    id: "retreatInstance",
    name: "Retreat Instance",
    displayField: "slug",
    fields: [
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      {
        id: "externalDateId",
        name: "External Date Id",
        type: "Symbol",
        required: true,
        validations: [{ unique: true }],
      },
      { id: "templateSlug", name: "Template Slug", type: "Symbol", required: true },
      { id: "startDate", name: "Start Date", type: "Date", required: true },
      { id: "endDate", name: "End Date", type: "Date", required: true },
      { id: "availableSpaces", name: "Available Spaces", type: "Integer", required: true },
      { id: "totalSpaces", name: "Total Spaces", type: "Integer", required: true },
      { id: "earlyBirdPrice", name: "Early Bird Price", type: "Integer", required: true },
      { id: "normalPrice", name: "Normal Price", type: "Integer", required: true },
      { id: "earlyBirdDeadline", name: "Early Bird Deadline", type: "Date", required: true },
      { id: "currency", name: "Currency", type: "Symbol", required: true },
      { id: "roomOptions", name: "Room Options", type: "Object" },
    ],
  },
  {
    id: "authorProfile",
    name: "Author Profile",
    displayField: "name",
    fields: [
      { id: "name", name: "Name", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "role", name: "Role", type: "Symbol" },
      { id: "bio", name: "Bio", type: "Text", required: true },
      { id: "avatarImageUrl", name: "Avatar Image Url", type: "Symbol" },
      { id: "avatarAlt", name: "Avatar Alt", type: "Symbol" },
      { id: "websiteUrl", name: "Website Url", type: "Symbol" },
      { id: "instagramHandle", name: "Instagram Handle", type: "Symbol" },
      { id: "isGuestContributor", name: "Is Guest Contributor", type: "Boolean" },
      { id: "active", name: "Active", type: "Boolean" },
    ],
  },
  {
    id: "blogPost",
    name: "Blog Post",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "coverImage", name: "Cover Image", type: "Symbol" },
      { id: "coverAlt", name: "Cover Alt", type: "Symbol" },
      { id: "excerpt", name: "Excerpt", type: "Text", required: true },
      { id: "content", name: "Content", type: "Text", required: true },
      {
        id: "authors",
        name: "Authors",
        type: "Array",
        items: {
          type: "Link",
          linkType: "Entry",
          validations: [{ linkContentType: ["authorProfile"] }],
        },
      },
      { id: "authorName", name: "Author Name", type: "Symbol" },
      { id: "publishDate", name: "Publish Date", type: "Date", required: true },
      { id: "tags", name: "Tags", type: "Array", items: { type: "Symbol" } },
      { id: "readTime", name: "Read Time", type: "Symbol" },
      { id: "isNewsletter", name: "Is Newsletter", type: "Boolean" },
      { id: "seoTitle", name: "SEO Title", type: "Symbol" },
      { id: "seoDescription", name: "SEO Description", type: "Text" },
    ],
  },
  {
    id: "testimonial",
    name: "Testimonial",
    displayField: "authorName",
    fields: [
      { id: "slug", name: "Slug", type: "Symbol", validations: [{ unique: true }] },
      { id: "quote", name: "Quote", type: "Text", required: true },
      { id: "authorName", name: "Author Name", type: "Symbol", required: true },
      { id: "authorCondition", name: "Author Condition", type: "Symbol" },
      {
        id: "service",
        name: "Service",
        type: "Symbol",
        validations: [{ in: ["yoga", "strength", "pt", "retreat", "small-group", "general"] }],
      },
      { id: "featured", name: "Featured", type: "Boolean" },
    ],
  },
  {
    id: "legalDocument",
    name: "Legal Document",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "version", name: "Version", type: "Symbol", required: true },
      { id: "effectiveDate", name: "Effective Date", type: "Date" },
      { id: "body", name: "Body", type: "Text", required: true },
      { id: "seoTitle", name: "SEO Title", type: "Symbol" },
      { id: "seoDescription", name: "SEO Description", type: "Text" },
    ],
  },
  {
    id: "faqItem",
    name: "FAQ Item",
    displayField: "question",
    fields: [
      { id: "question", name: "Question", type: "Symbol", required: true },
      { id: "answer", name: "Answer", type: "Text", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "category", name: "Category", type: "Symbol" },
      {
        id: "targetPage",
        name: "Target Page",
        type: "Symbol",
        validations: [
          {
            in: [
              "general",
              "home",
              "classes",
              "classes-yoga",
              "classes-strength",
              "classes-small-groups",
              "pt",
              "pricing",
              "retreats",
              "retreat-detail",
              "schedule",
              "schedule-detail",
              "blog",
              "blog-post",
              "about",
              "contact",
            ],
          },
        ],
      },
      { id: "targetSection", name: "Target Section", type: "Symbol" },
      { id: "sortOrder", name: "Sort Order", type: "Integer" },
    ],
  },
  {
    id: "trustBadge",
    name: "Trust Badge",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "description", name: "Description", type: "Text" },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "iconKey", name: "Icon Key", type: "Symbol" },
    ],
  },
  {
    id: "contactBlock",
    name: "Contact Block",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "body", name: "Body", type: "Text" },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "email", name: "Email", type: "Symbol" },
      { id: "phone", name: "Phone", type: "Symbol" },
      { id: "ctaLabel", name: "CTA Label", type: "Symbol" },
      { id: "ctaHref", name: "CTA Href", type: "Symbol" },
    ],
  },
  {
    id: "announcementBanner",
    name: "Announcement Banner",
    displayField: "slug",
    fields: [
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "message", name: "Message", type: "Text", required: true },
      { id: "ctaLabel", name: "CTA Label", type: "Symbol" },
      { id: "ctaHref", name: "CTA Href", type: "Symbol" },
      { id: "active", name: "Active", type: "Boolean" },
    ],
  },
  {
    id: "leadMagnet",
    name: "Lead Magnet",
    displayField: "title",
    fields: [
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "hookText", name: "Hook Text", type: "Text", required: true },
      { id: "landingHeadline", name: "Landing Headline", type: "Symbol" },
      { id: "landingDescription", name: "Landing Description", type: "Text" },
      { id: "ctaLabel", name: "CTA Label", type: "Symbol" },
      { id: "emailSubject", name: "Email Subject", type: "Symbol", required: true },
      { id: "emailPreviewText", name: "Email Preview Text", type: "Symbol" },
      { id: "emailBody", name: "Email Body", type: "Text", required: true },
      {
        id: "deliveryType",
        name: "Delivery Type",
        type: "Symbol",
        required: true,
        validations: [{ in: ["link", "inline"] }],
      },
      { id: "assetUrl", name: "Asset URL", type: "Symbol" },
      { id: "active", name: "Active", type: "Boolean" },
      { id: "startAt", name: "Start At", type: "Date" },
      { id: "endAt", name: "End At", type: "Date" },
    ],
  },
  {
    id: "newsletterSignupContent",
    name: "Newsletter Signup Content",
    displayField: "slug",
    fields: [
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      {
        id: "activeLeadMagnet",
        name: "Active Lead Magnet",
        type: "Link",
        linkType: "Entry",
        required: true,
        validations: [{ linkContentType: ["leadMagnet"] }],
      },
      { id: "formPlaceholder", name: "Form Placeholder", type: "Symbol", required: true },
      { id: "buttonLabel", name: "Button Label", type: "Symbol", required: true },
      { id: "successMessage", name: "Success Message", type: "Symbol", required: true },
      { id: "consentText", name: "Consent Text", type: "Text", required: true },
      { id: "popupTitle", name: "Popup Title", type: "Symbol" },
      { id: "popupDescription", name: "Popup Description", type: "Text" },
    ],
  },
  {
    id: "transactionalEmailTemplate",
    name: "Transactional Email Template",
    displayField: "templateKey",
    fields: [
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "templateKey", name: "Template Key", type: "Symbol", required: true },
      { id: "subject", name: "Subject", type: "Symbol", required: true },
      { id: "previewText", name: "Preview Text", type: "Symbol" },
      { id: "htmlBody", name: "HTML Body", type: "Text", required: true },
      { id: "textBody", name: "Text Body", type: "Text" },
      {
        id: "status",
        name: "Status",
        type: "Symbol",
        validations: [{ in: ["draft", "approved"] }],
      },
    ],
  },
  {
    id: "newsletterTemplate",
    name: "Newsletter Template",
    displayField: "title",
    fields: [
      { id: "slug", name: "Slug", type: "Symbol", required: true, validations: [{ unique: true }] },
      { id: "title", name: "Title", type: "Symbol", required: true },
      { id: "subject", name: "Subject", type: "Symbol", required: true },
      { id: "previewText", name: "Preview Text", type: "Symbol" },
      { id: "body", name: "Body", type: "Text", required: true },
      { id: "sendDate", name: "Send Date", type: "Date" },
      {
        id: "segmentation",
        name: "Segmentation",
        type: "Symbol",
        validations: [{ in: ["all_subscribers"] }],
      },
      { id: "testMode", name: "Test Mode", type: "Boolean" },
      {
        id: "status",
        name: "Status",
        type: "Symbol",
        validations: [{ in: ["draft", "scheduled", "approved", "published"] }],
      },
    ],
  },
];
